### ISSUE TITLE
ZapparCamera not working in a VITE project

### ISSUE THREAD

**Issue by josepaulodelacruz** [zappar-xr/zappar-react-three-fiber-examples#2]
I tried your bare minimum sample project into vite/react compare the 2.
The sample source code is working perfectly fine, then my vite (react) project, I copied the sample source code. then run it. 
However camera is not working, I'm running it on my local ip server which I can access in my mobile device. I already allow camera permission but it render nothing except the model.

**Comment by nyan-left** [comment]
Hi @josepaulodelacruz ,

It would be handy if you could provide any error logs.



If you haven't done so already, Vite needs a little extra config to work with zappar-react-three-fiber :)

```ts
// vite.config.ts
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react-swc";
import basicSsl from "@vitejs/plugin-basic-ssl";
import { qrcode } from "vite-plugin-qrcode";

export default defineConfig({
  plugins: [react(), basicSsl(), qrcode()],
  optimizeDeps: {
    exclude: ["@zappar/zappar-react-three-fiber"],
    include: [
      "ua-parser-js",
      "zustand",
      "chevrotain",
      "lodash.pick",
      "lodash.omit",
      "stats.js",
      "prop-types",
      "lodash.clamp",
    ],
  },
});
```

```shell
$ npm install --save-dev vite-plugin-qrcode @vitejs/plugin-basic-ssl 
```

**Comment by nyan-left** [comment]
Here's a template project using vite https://github.com/nyan-left/uar-r3f-vite-ts-ft/tree/main
